### ISSUE TITLE
Suggestions for this project 

### ISSUE THREAD

**Issue by NeoHsu** [AndreasTang/loginSimulator#1]
Hi Andreas,
I saw this project and some suggestions for you :

- Suggest to use [commitizen](https://github.com/commitizen/cz-cli) for commit message that can explain more detail for your commit
- Suggest to use ESlint for [coding style](https://github.com/airbnb/javascript).
- Learn more CSS for RWD and [coding style](https://github.com/airbnb/css).
- This code is not enough for clean code pattern
- Use more features by Reat.js.

I hope some suggestions that can help you be better.

**Comment by AndreasTang** [comment]
Thank you for your suggestions.
I will try to improve the project.
